default_title: "airgabion - N°1 de la location de hutte de chasse"
meta_description: "Sur airgabion, louez une hutte de chasse à un autre passionné de gibier d'eau !"
meta_image: "logo-avatar-02.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@airgabion" #indispensable pour les Twitter Cards
