default_title: "beerandbed - Stay with a local from your network"
meta_description: "With beerandbed, Stay with a local from your network and save money!"
meta_image: "beerandbed-logo-simple.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@beerandbed" #indispensable pour les Twitter Cards
