default_title: "beerandbed - Stay with a local from your organisation"
meta_description: "With beerandbed, meet your peers around the world and save money!"
meta_image: "beerandbed-logo-simple.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@beerandbed" #indispensable pour les Twitter Cards
